### PR TITLE
Fixed #1039 - Indentation and MaximumLineLength configuration paramet…

### LINKED ISSUE #1039: Changing indentation settings is not effective
## Expected Behavior
When indentSize and continuationIndentSize are set to value other than 4 it should take it into consideration.

## Current Behavior
When I set indentSize and continuationIndentSize to 2, detekt-formatting still expects 4-space indentation. 

## Steps to Reproduce (for bugs)
1. Change indentation: indentSize and continuationIndentSize to 2 in default-detekt-config.yml
```
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
    continuationIndentSize: 2
```
2. Write code with 2-space indentation.
3. Run gradle detektCheck
4. Detekt reports error
```
Ruleset: formatting - ...
	Indentation - [PsiWhiteSpace] at ... 
```

## Context
It's not possible to change default indentation.

## Your Environment
* Version used: 1.0.0.RC8
* Operating System and version: Mac OS

### PR DESCRIPTION
**Pull request by ljazgar**
…ers are now properly passed to KTLint rules.

Names of properties of EditorConfig passed to KTLint rules are now correct.
Different formatting rules doesn't overwrite EditorConfig any more.

### CODE REVIEW

**Comment by ljazgar** [comment]
Fixes #1039

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+import com.github.shyiko.ktlint.core.EditorConfig
+
+/**
+ * Creates new EditorConfig by merging existing EditorConfig with properties values passed by parameters.
+ * Values of properties passed by parameters are more important than properties in sourceEditorConfig.
+ *
+ * @author Lukasz Jazgar
+ */
+fun EditorConfig.Companion.merge(sourceEditorConfig: EditorConfig?,
```
Comment (schalkms) [inline detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt]: Good!

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+																 indentSize: Int? = null,
+																 continuationIndentSize: Int? = null,
+																 maxLineLength: Int? = null,
+																 insertFinalNewline: Boolean? = null): EditorConfig =
+	EditorConfig.fromMap(
```
Comment (schalkms) [inline detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt]: The formatting for the parameters looks a bit odd. Is this just Github's diff view?!

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+		HashMap<String, String>().also {
+			copyProperty(it, "indent_size", indentSize, sourceEditorConfig)
+			copyProperty(it, "continuation_indent_size", continuationIndentSize, sourceEditorConfig)
+			copyProperty(it, "max_line_length", maxLineLength, sourceEditorConfig)
+			copyProperty(it, "insert_final_newline", insertFinalNewline, sourceEditorConfig)
+		}
+	)
+
+private fun copyProperty(map: MutableMap<String, String>, property: String, value: Any?,
+												 sourceEditorConfig: EditorConfig?) {
```
Comment (schalkms) [inline detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt]: Same formatting issue here?!

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt (hunk 2 above)
Comment (ljazgar) [reply detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt]: Yes, formatting of this file was completely broken.  Fixed.

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt (hunk 3 above)
Comment (ljazgar) [reply detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/EditorConfigMerge.kt]: Fixed.

**Comment by ljazgar** [comment]
To be honest, I don't know how to write test of this functionality.

**Comment by schalkms** [comment]
@ljazgar No worries. So far so good! There needs to be a way to inject the editorconfig into this rule. Maybe @arturbosch has an idea how to accomplish that.
