### PR TITLE
Ensure filesystems are created so paths can be gotten

### LINKED ISSUE #2503: FileSystemNotFoundException in detekt 1.7.0 when using --config-resource
## Expected Behavior
the config from a jar in the classpath should be used

## Observed Behavior
```
java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
	at java.base/java.nio.file.Path.of(Path.java:208)
	at java.base/java.nio.file.Paths.get(Paths.java:97)
	at io.gitlab.arturbosch.detekt.rules.documentation.LicenceHeaderLoaderExtension.init(LicenceHeaderLoaderExtension.kt:27)
	at io.gitlab.arturbosch.detekt.core.FileProcessorLocator.load(FileProcessorLocator.kt:18)
	at io.gitlab.arturbosch.detekt.core.DetektFacade$Companion.create(DetektFacade.kt:90)
	at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:33)
	at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:20)
```

## Steps to Reproduce
* include a detekt-config.yml in a jar that you put in the `-classpath` of the detekt cli
* run `java -classpath .... io.gitlab.arturbosch.detekt.cli.Main --input /path/to/src/main/kotlin --config-resource detekt-config.yml`

## Context
We include our detekt-config in a jar that we pull in via maven and run detekt via antrun plugin,b ut the above cli invokation shows the same issue.  Works fine in 1.6.0 but not in 1.7.0.

## Your Environment

* Version of detekt used: 1.7.0
* Version of Gradle used (if applicable): --
* Operating System and version: circle ci linux container
* Link to your project (if it's a public repository): 
https://app.circleci.com/jobs/github/trib3/leakycauldron/849 <-- failed build
https://github.com/trib3/leakycauldron/blob/master/parent-pom/pom.xml#L1302-L1344 <-- maven config

### PR DESCRIPTION
**Pull request by josephlbarnett**
When getting resources from the classpath, the ZipFileSystem
needs to be initialized manually.

Fixes #2503

### CODE REVIEW

File: detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Configurations.kt [hunk 1]
```diff
@@ -78,5 +79,10 @@ fun CliArgs.extractUris(): Collection<URI> {
     val pathUris = config?.let { MultipleExistingPathConverter().convert(it).map(Path::toUri) } ?: emptyList()
     val resourceUris = configResource?.let { MultipleClasspathResourceConverter().convert(it).map(URL::toURI) }
         ?: emptyList()
+    resourceUris.forEach {
+        runCatching {
+            FileSystems.newFileSystem(it, emptyMap<String, Any>())
```
Comment (arturbosch) [inline detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Configurations.kt]: Thanks for analyzing this issue!

I would prefer the second answer on [stackoverflow](https://stackoverflow.com/questions/25032716/getting-filesystemnotfoundexception-from-zipfilesystemprovider-when-creating-a-p)
```java
private FileSystem initFileSystem(URI uri) throws IOException
{
    try
    {
        return FileSystems.getFileSystem(uri);
    }
    catch( FileSystemNotFoundException e )
    {
        Map<String, String> env = new HashMap<>();
        env.put("create", "true");
        return FileSystems.newFileSystem(uri, env);
    }
}
```

Your code could be refactored to `resourceUris.forEach(checkFileSystem)`.

**Comment by schalkms** [comment]
@arturbosch this should be included in v1.7.1 in my opinion.
