### PR TITLE
Fixed protected member report in sealed class

### LINKED ISSUE #361: ProtectedMemberInFinalClass false positive in sealed class
I have a protected function in a sealed class that is used by child classes, but this warning is being triggered.

### PR DESCRIPTION
**Pull request by schalkms**
fixes #361

### CODE REVIEW

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ProtectedMemberInFinalClass.kt [hunk 1]
```diff
@@ -23,7 +23,8 @@ class ProtectedMemberInFinalClass(config: Config = Config.empty) : Rule(config)
 	override fun visitClassOrObject(classOrObject: KtClassOrObject) {
 		val isNotAbstract = !classOrObject.hasModifier(KtTokens.ABSTRACT_KEYWORD)
 		val isFinal = !classOrObject.hasModifier(KtTokens.OPEN_KEYWORD)
-		if (isNotAbstract && isFinal) {
+		val isNotSealed = !classOrObject.hasModifier(KtTokens.SEALED_KEYWORD)
+		if (isNotAbstract && isFinal && isNotSealed) {
```
Comment (Mauin) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ProtectedMemberInFinalClass.kt]: Should we add a test case for this?

Comment (schalkms) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ProtectedMemberInFinalClass.kt]: There is one. Look at `FinalKlass.kt` please.
