### PR TITLE
Do not report auto-corrected formatting issues

### LINKED ISSUE #1836: Check fails even if all issues got auto fixed
## Expected Behavior
If all found issues where automatically fixed the check/build should not fail.

## Observed Behavior
The check/build fails even if after auto fixing no issues exists.
If I run detekt a second time it passes.

## Steps to Reproduce
```
build:
  maxIssues: 1
formatting:
  active: true
  android: true
  autoCorrect: true
```
Introduce an issue which is auto correctable.
Run the detekt gradle task.

## Context
I want to use the same config/task to auto format/fix and check the result
(locally and on the ci server)

## Your Environment
* Version of detekt used: 1.0.0 (also tested with 1.0.0-RC15)
* Version of Gradle used (if applicable): Gradle 5.1.1
* Operating System and version: macOS Mojave

### PR DESCRIPTION
**Pull request by schalkms**
All auto-corrected issues do not add to the total issues count.
Closes #1836

### CODE REVIEW

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/DetektFacade.kt [hunk 1]
```diff
@@ -39,14 +40,21 @@ class DetektFacade(
...
             KtFileModifier().saveModifiedFiles(filesToAnalyze) {
                 notifications.add(it)
             }
         }
 
+        for ((key, value) in findings) {
+            findings[key] = value.filter {
+                val correctableCodeSmell = it as? CorrectableCodeSmell
+                correctableCodeSmell == null || !correctableCodeSmell.autoCorrectEnabled
+            }
```
Comment (schalkms) [inline detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/DetektFacade.kt]: Maybe there's an easier solution for that.

Comment (schalkms) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/DetektFacade.kt]: Some tests are still missing

Comment (arturbosch) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/DetektFacade.kt]: Consider extracting these two files into a function. This would make the code more readable.

**Comment by arturbosch** [comment]
So basically we will just print the notifications?

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/DetektFacade.kt (hunk 1 above)
Comment (schalkms) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/DetektFacade.kt]: Yes, definitely! Is there a better perhaps more performant way of adding this check?

**Comment by schalkms** [comment]
Should we also exclude it from the notifications part?

**Comment by jonas-arkulpa** [comment]
I would argue that if it got automatically fixed I do not care about any notification / report entry.
But there might be a use case I am currently not aware of.

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/DetektFacade.kt (hunk 1 above)
Comment (arturbosch) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/DetektFacade.kt]: Actually I do not like this filtering inside the core module.
Imo detekt should always report everything it finds. The reports or cli baseline are only allowed to filter the violations.

If we leave it that way some users may be interested in this notifications because detekt would be `too magic`. They could not turn them on via the report or config option.
So this should go into the `FindingsReport` then. Users interested in formatting notification can write a new report for this. 
What do you think?

Comment (schalkms) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/DetektFacade.kt]: Yes, I agree. I'll try to refactor this PR in the upcoming days.

> Users interested in formatting notification can write a new report for this.

This would be a good example of 3rd party report. I think this shouldn't go into detekt at all.

**Comment by schalkms** [comment]
@arturbosch I think we need to be careful here. I have two open questions:

1. If we filter the corrected formatting issues in the `FindingsReport`, it will still count to the **maxIssues** count.
2. What happens when the issues were corrected during the CI process but not locally on the developer machine, because the developer forgot to run `gradle build`. Files are reported and corrected on the CI. The commit that has been made on the developer machine doesn't include the autocorrected files. Since detekt doesn't report the corrected files there's divergence between the CI and dev machine behavior.

**Comment by arturbosch** [comment]
1. This sounds like a +1 for the `excludeCorrectable` property inside `build`. That way we have a generic way to handle such a case in all extensions.
2. Normally the CI should never auto correct anything, for this the user can use `autoCorrect = $System.property.IS_CI ? false : true`. So this will need further documentation.

Does this answer your concerns?

**Comment by schalkms** [comment]
@arturbosch please consider this commit as a property. This needs of course further refactoring.
Now the autocorrected issues are still counted in the `BuildFailureReport`. Hence, the build will fail, because the threshold is exceeded.

**Comment by arturbosch** [comment]
> @arturbosch please consider this commit as a property. This needs of course further refactoring.
> Now the autocorrected issues are still counted in the `BuildFailureReport`. Hence, the build will fail, because the threshold is exceeded.

As a property? Sorry for not understanding your sentence. The commit looks great. A property is the right way to go

**Comment by schalkms** [comment]
I meant prototype instead of property. The mentioned behavior still feels weird. Should we also exclude the fixed formatting issues from the `BuildFailureReport`?

**Comment by arturbosch** [comment]
Yes this property should be used in BuildFailureReport/Runner.

**Comment by schalkms** [comment]
@arturbosch I think that this in a mergeable state now. Could you please review this once again.
@sanogueralorenzo @jonas-arkulpa could you please test this out in your projects?

We should include this in v1.2.1

**Comment by jonas-arkulpa** [comment]
@schalkms I can have a look next week. Are there instructions to use the detekt version of this PR?

**Comment by schalkms** [comment]
@jonas-arkulpa Thanks for your help! 
- Check out this branch
- `cd detekt`
- `./gradlew build shadowJar`
- `java -jar detekt-cli/build/libs/detekt-cli-[version]-all.jar`

File: detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/BuildFailure.kt [hunk 2]
```diff
@@ -13,9 +14,12 @@ private val WEIGHTED_ISSUES_COUNT_KEY = Key.create<Int>("WEIGHTED_ISSUES_COUNT")
 private const val BUILD = "build"
 private const val WEIGHTS = "weights"
 private const val MAX_ISSUES = "maxIssues"
+private const val EXCLUDE_CORRECTABLE = "excludeCorrectable"
```
Comment (schalkms) [inline detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/BuildFailure.kt]: This property needs to be added somewhere to the `detekt-config.yml` file.

File: detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/AutoCorrectLevelSpec.kt [hunk 3]
```diff
@@ -30,34 +30,6 @@ class AutoCorrectLevelSpec : Spek({
             }
         }
 
-        describe("autoCorrect: false on top level") {
-
-            val config = yamlConfig("/autocorrect/autocorrect-toplevel-false.yml")
-
-            it("should format the test file but not print to disc") {
```
Comment (arturbosch) [inline detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/AutoCorrectLevelSpec.kt]: Mh, I do not understand this removal. We do not have any test case that tests if actually a file was formatted after running detekt with autoCorrect?

File: detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/BuildFailure.kt (hunk 2 above)
Comment (arturbosch) [reply detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/BuildFailure.kt]: This should go into the ConfigPrinter -> https://github.com/arturbosch/detekt/blob/6c3795554f24377920664bb08833202679c8a3d4/detekt-generator/src/main/kotlin/io/gitlab/arturbosch/detekt/generator/printer/rulesetpage/ConfigPrinter.kt#L68

Comment (schalkms) [reply detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/BuildFailure.kt]: Addressed this in the second to last commit. Furthermore, I rebased my branch.
I'm sorry, that this PR took me so long.

File: detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/AutoCorrectLevelSpec.kt (hunk 3 above)
Comment (schalkms) [reply detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/AutoCorrectLevelSpec.kt]: Agreed. I addressed this in the last commit. This is good to go for v1.3.1.

**Comment by jonas-arkulpa** [comment]
Works like charm in the new version.

@schalkms sry I tried to test it last year and had some issues and limited time.
