### PR TITLE
Use argsfiles for CI

### LINKED ISSUE #2318: Allow Detekt CLI to take an args file.
When using Detekt in the Uber monorepo, we've run into issues with extremely long argument lists that result in "Argument list too long" exceptions in the build, for things like Classpath or source lists. We've worked around it for now by trimming down our use of absolute paths in a custom Buck genrule.

Detekt CLI should have the ability to take an args file containing this information to work with larger argument lists that exceed the shell limits.

### PR DESCRIPTION
**Pull request by arturbosch**
Closes #2318

### CODE REVIEW

**Comment by 3flex** [comment]
Apparently JCommander supports this natively? https://jcommander.org/#_syntax

**Comment by arturbosch** [comment]
Ah nice, good to know, thx!

File: detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Main.kt [hunk 1]
```diff
@@ -9,13 +9,27 @@ import io.gitlab.arturbosch.detekt.cli.runners.Executable
...
+        var arguments = args
+        if (shouldUseArgumentsFile()) {
+            val argsFile = args.first().removePrefix("@")
+            arguments = File(argsFile).useLines { seq ->
+                seq.flatMap { it.splitToSequence(" ") }
+                    .filterNot { it.isBlank() }
+                    .toList()
+                    .toTypedArray()
+            }
+        }
```
Comment (schalkms) [inline detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Main.kt]: If we stick with this solution, this code should have two corresponding tests.
This could work with a refactoring step.

**Comment by 3flex** [comment]
Just FYI @arturbosch you need to remove the hyphen from your initial description to automatically close the linked issue.

Use
`Closes #2318`
Not
`Closes - #2318`

**Comment by arturbosch** [comment]
Thanks for your comments!
JCommander really supports argsfiles out of the box so we do not need to add any code.
