### PR TITLE
SwallowedException: fix false negative when using variables

### LINKED ISSUE #2049: SwallowedException false negative
## Expected Behavior
The following code block should be considered non-compliant:

    try {
    } catch (e: IllegalStateException) {
        var message = e.message  // e is swallowed
        throw IllegalArgumentException(message)
    } catch (f: Exception) {
        var message = f.toString()  // f is swallowed
        throw Exception(IllegalArgumentException(message))
    }

## Observed Behavior
Code passes the SwalowedException check

## Steps to Reproduce
Use the sample code provided, or similar where exception message is stored and passed into new exception.

## Context
Trying to prevent instances of swallowed exceptions

## Your Environment

* Version of detekt used: 1.1.x
* Version of Gradle used (if applicable): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): N/A

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #2049

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedExceptionSpec.kt [hunk 1]
```diff
@@ -37,6 +37,22 @@ class SwallowedExceptionSpec : Spek({
             assertThat(subject.compileAndLint(code)).hasSize(2)
         }
 
+        it("reports swallowed exceptions only using exception strings via variables") {
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedExceptionSpec.kt]: A test case that asserts conditional code could be beneficial.
e.g.
```Kotlin
catch (e: IllegalStateException) {
  if (...) {
    val message = e.message
    throw IllegalArgumentException(message)
  }
} 
```

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedException.kt [hunk 2]
```diff
@@ -91,26 +94,36 @@ class SwallowedException(config: Config = Config.empty) : Rule(config) {
...
         val parameterName = catchClause.catchParameter?.name
+        val parameterNameReferencesInVariables = catchClause.catchBody?.children?.mapNotNull { child ->
+            val variable = child as? KtProperty ?: return@mapNotNull null
+            val variableName = variable.name ?: return@mapNotNull null
+            val parameterReference = when (val initializer = variable.initializer) {
+                is KtNameReferenceExpression -> initializer.takeIf { it.text == parameterName }
+                is KtDotQualifiedExpression -> initializer.receiverExpression.takeIf { it.text == parameterName }
+                else -> null
+            } ?: return@mapNotNull null
+            variableName to parameterReference
```
Comment (schalkms) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedException.kt]: This would be easier to maintain and understand if we refactor this into a separate method.

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedException.kt [hunk 3]
```diff
@@ -91,26 +94,36 @@ class SwallowedException(config: Config = Config.empty) : Rule(config) {
...
+        }.orEmpty().toMap()
```
Comment (schalkms) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedException.kt]: Could we return an `emptyMap()` instead of null pointer? Then we could spare the `orEmpty()` call.

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedException.kt [hunk 4]
```diff
@@ -91,26 +94,36 @@ class SwallowedException(config: Config = Config.empty) : Rule(config) {
...
+                        val referenceText = reference.text
+                        if (referenceText == parameterName) {
+                            reference.getQualifiedExpressionForReceiverOrThis()
+                        } else {
+                            parameterNameReferencesInVariables[referenceText]?.getQualifiedExpressionForReceiverOrThis()
+                        }
+                    }
+                    .orEmpty()
+               return parameterNameReferences.isNotEmpty() &&
+                       parameterNameReferences.all { it is KtDotQualifiedExpression }
```
Comment (schalkms) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedException.kt]: This would be easier to maintain and understand if we refactor this into a separate method.

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedExceptionSpec.kt [hunk 5]
```diff
@@ -37,6 +37,42 @@ class SwallowedExceptionSpec : Spek({
...
+
+        it("reports swallowed exceptions only using exception strings via variables in 'if' block") {
+            val code = """
+                fun f() {
+                    try {
+                    } catch (e: IllegalStateException) {
+                        if (true) {
+                            val message = e.message
+                            throw IllegalArgumentException(message)
+                        }
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedExceptionSpec.kt]: What happens when the user has a construct like this? Is it reported? The exception only gets swallowed when the `condition` is true in that case.

```kotlin
catch (f: Exception) {
  if (condition) {
    val message = f.toString()
    throw Exception(IllegalArgumentException(message))
  }
  throw IllegalStateException(f)
}
```

Comment (schalkms) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/SwallowedExceptionSpec.kt]: An additional test for this case might be worthwhile.
