### PR TITLE
Check jcenter repository present in Gradle plugin

### LINKED ISSUE #2549: Adding Detekt to a project from scratch, detektGenerateConfig is broken
## Expected Behavior
The task should generate the config for Detekt in a new project when run

## Observed Behavior
The task fails with error:

```
Could not determine the dependencies of task ':detektGenerateConfig'.
> Could not resolve all task dependencies for configuration ':detekt'.
   > Cannot resolve external dependency io.gitlab.arturbosch.detekt:detekt-cli:1.7.2 because no repositories are defined.
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Yes, the `required by` and `project` fields are actually empty, I didn't omit anything.

## Steps to Reproduce
Added to an existing codebase with a composite build structure. Structure:

```
<root>
  - composite build: A
    - module A1
    - module A2...
  - composite build: B
    - module B1...
  - composite build: C
  - composite build: D
```

I am currently operating from the root project, but adding Detekt to composite build A. Operating directly from project A's folder (so this is now from Gradle's perspective any regular project) yields the same result. 

## Context
Haven't tried any other tasks yet — I can't even get the build to generate the config file, so not much of a point to. I have followed the "getting started" section on the website, so I have added to composite build A's `build.gradle.kts`:

```kotlin
import io.gitlab.arturbosch.detekt.*
import kpm.server.gradle.*
import org.gradle.kotlin.dsl.detekt
import org.jetbrains.kotlin.gradle.tasks.*

buildscript {
    repositories {
        jcenter()
    }
}

plugins {
    `java-library`
    id("org.jetbrains.kotlin.jvm") apply false
    id("com.github.ben-manes.versions") version "0.28.0"
    id("io.gitlab.arturbosch.detekt") version "1.7.2"
}

// ...

subprojects {
    buildscript {
        repositories {
            jcenter()
        }
    }

    apply(plugin = "io.gitlab.arturbosch.detekt")

    // ...

    repositories {
        maven(url = "https://dl.bintray.com/kotlin/ktor")
        maven(url = "https://dl.bintray.com/kotlin/kotlinx")
        maven(url = "https://dl.bintray.com/kotlin/kotlinx.html")

        // ... private repos

        mavenCentral()
        jcenter()
    }

    detekt {
        toolVersion = "1.7.2"
    }

    dependencies {
        // ... other dependencies
        detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.7.2")
    }

    tasks.withType<Detekt> {
        this.jvmTarget = "1.8"
    }

    // ...
}
```

## Your Environment
* Version of detekt used: 1.7.2
* Version of Gradle used (if applicable): 6.3
* Operating System and version: macOS Catalina
* Link to your project (if it's a public repository): N/A

### PR DESCRIPTION
**Pull request by rock3r**
This PR fixes #2549 by adding a log when the user doesn't have `jcenter()` configured in their project, by emitting an error with a clear warning and resolution instructions.

I have run all the tests in the project and smoke tested the plugin locally.

### CODE REVIEW

File: detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/GradleProjectChecks.kt [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+internal fun checkRequiredRepositoriesAreConfiguredOn(project: Project) {
+    project.afterEvaluate {
+        val missingJCenter = project.repositories.none {
+            it is MavenArtifactRepository && it.url == bintrayJCenterUri
+        }
+
+        if (missingJCenter) {
+            project.logger.error(
+                "The project ${project.path} doesn't have the jcenter() repository in its repositories list; " +
```
Comment (schalkms) [inline detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/GradleProjectChecks.kt]:
```suggestion
                "The project ${project.path} doesn't have the jcenter() repository in its repositories list. " +
```

File: detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/GradleProjectChecks.kt [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+                        "this is required for Detekt to work correctly. Please add jcenter() to the project's " +
```
Comment (schalkms) [inline detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/GradleProjectChecks.kt]:
```suggestion
                        "This is required for Detekt to work correctly. Please add jcenter() to the project's " +
```

**Comment by mtraynham** [comment]
Is there any way to disable this?  Currently using Nexus with a proxy repository.

**Comment by rock3r** [comment]
No, but it's just a log message. It doesn't stop the build in and by itself.

**Comment by BraisGabin** [comment]
🤔 I know nearly nothing about gradle plugins but... Could we launch this message only if it fails? As a hint about what could be happening?

**Comment by rock3r** [comment]
To be able to do that you'd have to check if the dependency is available on the classpath of the modules after the project is synced... possibly doable but a bit beyond my Gradle knowledge :)

**Comment by runningcode** [comment]
We use a maven proxy so this disallows us from upgrading. I'll file a new issue.

**Comment by rock3r** [comment]
Again, the plugin will work just fine, it's just emitting a log entry that you can ignore.

**Comment by runningcode** [comment]
I understand, but in our app with over 100 modules its printed to the console over 100 times as an "error". Let's keep the discussion going on this issue: https://github.com/arturbosch/detekt/issues/2571#issuecomment-607921814
