### PR TITLE
Silence report if containing no findings

### LINKED ISSUE #1854: Silent mode still produces output
## Expected Behavior
Silent mode produces no output if no issues are found

## Observed Behavior
Empty lines/newlines are printed out when `detekt` task is executed

## Steps to Reproduce
Relevant configuration piece:
```yaml
processors:
  active: false

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
```

I do want findings to be printed out **if** there are violations. I'd expect with such configuration and no violations, `detekt` will be completely silent. Instead, it produces empty lines (if a task produces no lines, it's not visible it Gradle's output. Also there's clearly vertical space after the task, whereas other Gradle tasks don't have this space)

Actual output:
```
> Task :lint-checks:detekt


> Task :data:room-storage:detekt


> Task :common:testing:detekt


> Task :domain:detekt


> Task :app:detekt


> Task :data:graphql-networking:detekt


> Task :presentation:ui:detekt


```

## Your Environment
* Version of detekt used: 1.0.1
* Version of Gradle used (if applicable): 5.6.1
* Operating System and version: macos

### PR DESCRIPTION
**Pull request by schalkms**
The `FindingsReport` should not produce any output if there are no
code smells at all.
This fixes #1854

### CODE REVIEW

File: detekt-cli/src/test/kotlin/io/gitlab/arturbosch/detekt/cli/console/FindingsReportSpec.kt [hunk 1]
```diff
@@ -37,7 +37,15 @@ class FindingsReportSpec : Spek({
...
         it("reports no findings") {
             val detektion = TestDetektion()
-            assertThat(subject.render(detektion)).isEmpty()
+            assertThat(subject.render(detektion)).isNull()
+        }
+
+        it("reports no findings with rule set containing no smells") {
+            val detektion = object : TestDetektion() {
+                override val findings: Map<String, List<Finding>> = mapOf(
+                    Pair("EmptySmells", emptyList()))
```
Comment (arturbosch) [inline detekt-cli/src/test/kotlin/io/gitlab/arturbosch/detekt/cli/console/FindingsReportSpec.kt]: We have a rule to not use Pair... But x to y instead :)

Comment (schalkms) [reply detekt-cli/src/test/kotlin/io/gitlab/arturbosch/detekt/cli/console/FindingsReportSpec.kt]: That will be refactored anyway.

Comment (schalkms) [reply detekt-cli/src/test/kotlin/io/gitlab/arturbosch/detekt/cli/console/FindingsReportSpec.kt]: Currently, there are many usages in our codebase. I leave this one for now.
