### PR TITLE
Fix #1027 - FunctionOnlyReturningConstant

### LINKED ISSUE #1027: FunctionOnlyReturningConstant false positive for interfaces with default implementations
## Expected Behavior
This should not trigger the `FunctionOnlyReturningConstant` rule.
```
interface InterfaceFunctionReturningConstant {
 	fun interfaceFunctionWithImplementation() = 1
}
```

## Current Behavior
It tells me I should just declare a constant.  `isOpen()` returns `false` on the `KtNamedFunction`.

## Steps to Reproduce (for bugs)
Failing test case: https://github.com/scottkennedy/detekt/commit/58691e872b1cbb5731bb1071f1b80be5bd35aca6

I couldn't quickly figure out how to identify an interface like this, or I would have just fixed it.

### PR DESCRIPTION
**Pull request by schalkms**

### CODE REVIEW

**Comment by schalkms** [comment]
@scottkennedy please have a look at this PR

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/FunctionOnlyReturningConstant.kt [hunk 1]
```diff
@@ -52,7 +53,14 @@ class FunctionOnlyReturningConstant(config: Config = Config.empty) : Rule(config
 	}
 
 	private fun checkOverridableFunction(function: KtNamedFunction) =
-			if (ignoreOverridableFunction) !function.isOverridden() && !function.isOpen() else true
+			if (ignoreOverridableFunction)
+				!function.isOverridden() && !function.isOpen() && !checkContainingInterface(function)
```
Comment (arturbosch) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/FunctionOnlyReturningConstant.kt]: Lets please use braces here
