### PR TITLE
Consider double colon references for class usages - Closes #1390

### LINKED ISSUE #1390: False positive UnusedPrivateClass when using class references
```kotlin
package my.pkg

import org.junit.jupiter.api.Test
import kotlin.test.assertNotEquals

class UnusedPrivateClassTest {

    private data class SomeClass(val name: String)

    private data class AnotherClass(val id: Long)

    @Test
    fun `verify class is used`() {
        val instance = SomeClass(name = "test")
        assertNotEquals(AnotherClass::class.java.simpleName, instance::class.java.simpleName)
    }
}
```

## Expected Behavior
No issues reported as `AnotherClass` is clearly referenced.

## Observed Behavior
`UnusedPrivateClass` violation.

## Steps to Reproduce
See the code above

## Context
In our library we are using reflections to build objects and corresponding unit tests verify the correct objects get created. This leads to a lot of unnecessary suppressions - see https://github.com/ExpediaDotCom/graphql-kotlin/pull/91

## Your Environment
* Version of detekt used: RC12
* Link to your project (if it's a public repository): https://github.com/ExpediaDotCom/graphql-kotlin

### PR DESCRIPTION
**Pull request by arturbosch**

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateClassSpec.kt [hunk 1]
```diff
@@ -278,5 +278,26 @@ class UnusedPrivateClassSpec : SubjectSpek<UnusedPrivateClass>({
 
 			assertThat(findings).isEmpty()
 		}
+
+		it("verifies the fix for double colon references - #1390") {
```
Comment (Mauin) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateClassSpec.kt]: Should we give this a more general name? Something along the lines of `it("does not report classes that are used with ::class")`

Comment (arturbosch) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateClassSpec.kt]: +1, done.
