### PR TITLE
Do only consider calls and member accesses in UnnecessaryApply rule

### LINKED ISSUE #1473: False Positive UnnecessaryApply
## Expected Behavior
No UnnecessaryApply

## Observed Behavior
UnnecessaryApply

## Steps to Reproduce
```kt
    fun detektFalsePositive() {
        Preference(context).apply { // This one does not trigger
            summary = "test"
            isEnabled = false
        }

        Preference(context).apply { // This triggers UnnecessaryApply
            if (shouldDisable()) {
                summary = "test"
                isEnabled = false
            }
        }
    }
```

In my project the Android Preference is the return value from another function, so I can't put the if statement around the whole thing.

## Your Environment
* Version of detekt used: RC13
* Version of Gradle used (if applicable): 5.2.1
* Operating System and version: Various
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by arturbosch**
Closes #1473

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApplySpec.kt [hunk 1]
```diff
@@ -123,5 +123,38 @@ class UnnecessaryApplySpec : Spek({
...
+                        fun shouldDisable() = true
+                    }
+                    fun falsePositive() {
+                        Preference().apply {
+                            if (shouldDisable()) {
+                                // actions
+                            }
+                        }
+                    }
+			    """.trimIndent())).isEmpty()
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApplySpec.kt]: weird formatting here

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApplySpec.kt [hunk 2]
```diff
@@ -123,5 +123,38 @@ class UnnecessaryApplySpec : Spek({
...
+                    fun correctReporting() {
+                        Preference().apply {
+                            propertyAccess
+                        }
+
+                        Preference().apply {
+                            this.propertyAccess
+                        }
+                    }
+			    """.trimIndent())).hasSize(2)
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApplySpec.kt]: weird formatting here

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt [hunk 3]
```diff
@@ -64,9 +66,14 @@ private fun KtCallExpression.receiverIsUnused(): Boolean {
...
     if (lambdaBody.hasOnlyOneStatement()) {
-        return lambdaBody.statements[0]
+        val expr = lambdaBody.statements[0]
+        val notAnAssignment = expr
                 ?.safeAs<KtBinaryExpression>()
                 ?.operationToken != KtTokens.EQ
+        val isMemberAccess = expr is KtReferenceExpression ||
+                expr is KtCallExpression ||
+                expr.safeAs<KtDotQualifiedExpression>()?.receiverExpression is KtThisExpression
+        return notAnAssignment && isMemberAccess
```
Comment (schalkms) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt]: I would refactor this. From an algorithmic perspective `isMemberAccess` is evaluated even if `notAnAssignment` is false.
