### PR TITLE
 Fixed bug reporting false positives with EmptyFunctionBlock

### LINKED ISSUE #1684: EmptyFunctionBlock false positive: overridden function with comment in body
detekt 1.0.0-RC15

This gets reported by EmptyFunctionBlock as violation:
```kotlin
override fun fetch() {
    // No-op
}
```

There is `ignoreOverriddenFunctions` but I don't want to ignore all overridden functions, just ones with a comment in their body.

### PR DESCRIPTION
**Pull request by cortinico**
This rule (EmptyFunctionBlock) had a bug in reporting functions with override and empty
blocks (with or without comments). 

I'm fixing it and adding a couple of tests to make sure it works properly.

Fixes #1684

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt [hunk 1]
```diff
@@ -75,5 +75,33 @@ class EmptyFunctionBlockSpec : Spek({
...
+                        // no-op
+                    }
+
+                    override fun listenThat() {
+
+                    }
+                }
+            """.trimIndent()
+            it("should not flag overridden functions with commented body") {
+                assertThat(subject.compileAndLint(code)).hasSize(1)
```
Comment (rock3r) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: I'd avoid using `hasSize()` to assert things — we've been bitten by it in the past. I know that most tests still use it but that gives no guarantees (except in the case of `isEmpty()`/`hasSize(0)`), because code changes may remove the correct detection and replace it with a wrong one. In this example, it may switch to flag `listenThat()` and we'd be none the wiser.

Please use `FindingsAssertions`' own `hasLocationStrings()` and match on the location(s) detected instead.

File: detekt-rules/src/test/resources/cases/Empty.kt [hunk 2]
```diff
@@ -19,10 +19,6 @@ class Empty : Runnable {
 
     }
 
-    fun emptyMethod() {
```
Comment (rock3r) [inline detekt-rules/src/test/resources/cases/Empty.kt]: Why was this removed?

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlock.kt [hunk 3]
```diff
@@ -7,9 +7,12 @@ import org.jetbrains.kotlin.psi.KtNamedFunction
 
 /**
  * Reports empty functions. Empty blocks of code serve no purpose and should be removed.
- * This rule will not report functions overriding others.
+ * This rule will report all the functions with an empty body, with an exception: overriding functions with a
```
Comment (rock3r) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlock.kt]: Maybe terser:

>This rule will not report functions with the `override` modifier that have a comment as their only body contents (e.g., a `// no-op` comment in an unused listener function)

File: docs/pages/documentation/empty-blocks.md [hunk 4]
```diff
@@ -74,7 +74,10 @@ Reports empty `for` loops. Empty blocks of code serve no purpose and should be r
 ### EmptyFunctionBlock
 
 Reports empty functions. Empty blocks of code serve no purpose and should be removed.
-This rule will not report functions overriding others.
+This rule will report all the functions with an empty body, with an exception: overriding functions with a
```
Comment (rock3r) [inline docs/pages/documentation/empty-blocks.md]: This is autogen'd from the kt class so it will change accordingly :)

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlock.kt [hunk 5]
```diff
@@ -7,9 +7,12 @@ import org.jetbrains.kotlin.psi.KtNamedFunction
...
+ * comment in the body (e.g. a `// no-op` comment).
  *
- * @configuration ignoreOverriddenFunctions - excludes overridden functions with an empty body (default: `false`)
+ * To ignore all the override functions, please use the [ignoreOverriddenFunctions] configuration field.
+ *
+ * @configuration ignoreOverriddenFunctions - Excludes all the overridden functions (default: `false`).
```
Comment (rock3r) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlock.kt]: Don't put the dot at the end — the string is manipulated when generating the markdown and it will result in a weird entry in the doc with a superfluous space — see [further down](https://github.com/arturbosch/detekt/pull/1690/files#diff-81f6dd5347eb6b688ca081c05000c30bR90).

**Comment by rock3r** [comment]
Also the CI says you have conflicts :P

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlock.kt [hunk 6]
```diff
@@ -28,6 +31,7 @@ class EmptyFunctionBlock(config: Config) : EmptyRule(config) {
         val bodyExpression = function.bodyExpression
         if (!ignoreOverriddenFunctions) {
             if (function.isOverride()) {
+                // If this function is an override, let's ignore empty bodies with comments.
```
[the remark this answers is not in the document]
Comment (cortinico) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlock.kt]: Sort of, although the logic here is a bit intricate imho. Anyway I'm removing it, I don't have a strong opinion on this.

File: detekt-rules/src/test/resources/cases/Empty.kt (hunk 2 above)
Comment (cortinico) [reply detekt-rules/src/test/resources/cases/Empty.kt]: Because the test:
```kotlin
it("findsEmptyFun") {
            test { EmptyFunctionBlock(Config.empty) }
}

[...]
private fun test(block: () -> Rule) {
    val rule = block()
    rule.lint(compileForTest(Case.Empty.path()))
    assertThat(rule.findings).hasSize(1)
}
```
inside EmptyCodeSpek.kt:92 was failing. The failure was triggered by having two empty functions inside the `Empty.kt` file (`override fun run()` and `fun emptyMethod()`). So either we update the `test(block: () -> Rule)` to have the number of expected issues as parameter (with maybe `1` as default value) or we just cleanup the `Empty.kt` file. I went for the latter solution.

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlock.kt (hunk 5 above)
Comment (cortinico) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlock.kt]: Oh damn 😅

**Comment by cortinico** [comment]
> Also the CI says you have conflicts :P

Yeah I should update my master from time to time 😆

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt (hunk 1 above)
Comment (cortinico) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: Agree 👍 I've added `0560f0a15f2ad2f03eebe25f076807aa93835fe7` that contains this fix.
Although I have the strong feeling that the `hasLocationStrings()` is not properly working. Apparently failures are not raised to Spek, and tests are marked as green also if the assertion is not met. I'm going to investigate a bit further and open another PR.

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt [hunk 7]
```diff
@@ -22,7 +25,7 @@ class EmptyFunctionBlockSpec : Spek({
                 class A {
                     protected fun stuff() {}
                 }"""
-            assertThat(subject.compileAndLint(code)).hasSize(1)
+            assertThat(subject.compileAndLint(code)).hasLocationStrings("'{}' at (2,27) in /$fileName")
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: I would write it like this to also check that there is exactly 1 finding.

```Kotlin
val findings = subject.compileAndLint(code)
assertThat(findings).hasSize(1)
assertThat(findings).hasLocationStrings("...")
```

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt [hunk 8]
```diff
@@ -38,7 +41,7 @@ class EmptyFunctionBlockSpec : Spek({
 				fun a() {
 					fun b() {}
 				}"""
-            assertThat(subject.compileAndLint(code)).hasSize(1)
+            assertThat(subject.compileAndLint(code)).hasLocationStrings("'{}' at (2,10) in /$fileName")
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: same here

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt [hunk 9]
```diff
@@ -72,7 +75,36 @@ class EmptyFunctionBlockSpec : Spek({
 
             it("should not flag overridden functions") {
                 val config = TestConfig(mapOf(EmptyFunctionBlock.IGNORE_OVERRIDDEN_FUNCTIONS to "true"))
-                assertThat(EmptyFunctionBlock(config).compileAndLint(code)).hasSize(1)
+                assertThat(EmptyFunctionBlock(config).compileAndLint(code)).hasLocationStrings("'{}' at (1,13) in /$fileName")
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: same here

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt [hunk 10]
```diff
@@ -72,7 +75,36 @@ class EmptyFunctionBlockSpec : Spek({
...
+                        // no-op
+                    }
+
+                    override fun listenThat() {
+
+                    }
+                }
+            """.trimIndent()
+            it("should not flag overridden functions with commented body") {
+                assertThat(subject.compileAndLint(code))
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: same here

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt (hunk 1 above)
Comment (rock3r) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: Hm, not sure if it's broken since I last used it tbh, worth checking!

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt (hunk 7 above)
Comment (rock3r) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: I seem to remember `hasLocationStrings()` should be checking that too? If not, probably worth creating a `hasExactlyLocationStrings()` that checks the count too, seems useful.

Comment (schalkms) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: `hasLocationStrings()` does not check this.
I would also prefer your solution with `hasExactlyLocationStrings()`.
Thanks for the comment @rock3r

Comment (cortinico) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: Agree 👍 Pushed 0ac2a8dd2df6674daabee492104a7bed4d58516b with the updated assertion logic.

**Comment by cortinico** [comment]
This should be good to go now imho

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt (hunk 1 above)
Comment (cortinico) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: @rock3r Yup was broken #1706 :/

Comment (rock3r) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyFunctionBlockSpec.kt]: Dang! I hope I'll have some time to fix it soon™
