### PR TITLE
Exit process with specific code when detekt finds code issues

### LINKED ISSUE #1493: Add "issues found" exit code
## Expected Behavior
Exit codes allow differentiation between:
* Successful run, no issues found/flagged
* Successful run, issues found (`BuildFailure`)
* CLI parameters could not be parsed (`ParameterException`)
* Unrecoverable error/exception occurred (all other exceptions)

## Current Behavior
Exit code for "Unrecoverable error/exception occurred" and "Successful run, issues found" are the same (`1`)

## Context
To implement a feature for https://github.com/arturbosch/detekt/issues/1435 it must be possible to detect the difference between "Unrecoverable error/exception occurred" and "Successful run, issues found", as only "Successful run, issues found" should be ignored when `ignoreFailures` is enabled in the Gradle plugin.

Propose the following:

| Exit code | Description                              |
|-----------|------------------------------------------|
| 0         | Command completed successfully, no issues found |
| 1         | An error occurred                        |
| 2         | detekt ran successfully, issues found    |

Exit code `1` would be used for all exceptions.

Additional codes can be added in future depending on use case, but this would be enough to build a feature for https://github.com/arturbosch/detekt/issues/1435.

### PR DESCRIPTION
**Pull request by 3flex**
Closes #1493 

detekt will exit with one of the following exit codes:

| Exit code | Description                                                                                     |
|-----------|-------------------------------------------------------------------------------------------------|
| 0         | detekt ran normally and maxIssues or failThreshold count was not reached in BuildFailureReport. |
| 1         | An unexpected error occurred                                                                    |
| 2         | maxIssues or failThreshold count was reached in BuildFailureReport.                             |

### CODE REVIEW

File: detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Main.kt [hunk 1]
```diff
@@ -21,7 +24,17 @@ fun main(args: Array<String>) {
         arguments.printAst -> AstPrinter(arguments)
         else -> Runner(arguments)
     }
-    executable.execute()
+    try {
+        executable.execute()
+    } catch (e: BuildFailure) {
+        // maxIssues or failThreshold count was reached
```
Comment (vanniktech) [inline detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Main.kt]: nit: comments should be sentences. https://nedbatchelder.com/blog/201401/comments_should_be_sentences.html

**Comment by 3flex** [comment]
I looked into testing but it's a little tricky: https://stackoverflow.com/questions/309396/java-how-to-test-methods-that-call-system-exit

I'll be working on #1435 next and integration tests will cover the exit codes 1 & 2.

Will update comments and docs according to your suggestions, thanks!
