### PR TITLE
UnnecessaryApply: fix false positive when it's used as an expression

### LINKED ISSUE #2435: UnnecessaryApply false positive cases
## Expected Behavior
```
                    val content = if (5 >= 3) {
                        Intent().apply { putExtra("", 1) }
                    } else {
                        Intent()
                    }
```
// Used as an assignment

```
                    fun printCountry(block: () -> Intent) {
                        println(block())
                    }
                    fun main() {
                        printCountry {
                            println("Does nothing")
                            Intent().apply { putExtra("COUNTRY", "us") }
                        }
                    }
```
//Used as the last statement of a block inside lambda.

Both cases should not report an error as the receiver of the apply is used.

## Observed Behavior
Both cases have an error reported.

## Context
I am applying detekt to my company's codebase and find these unexpected behaviors.

## Your Environment
* Version of detekt used: 1.7.0-beta2 (Latest trunk)

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #2435

### CODE REVIEW

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt [hunk 1]
```diff
@@ -53,14 +56,18 @@ class UnnecessaryApply(config: Config) : Rule(config) {
...
 
-private fun KtCallExpression.receiverIsUnused(): Boolean = when (parent) {
+private fun KtCallExpression.receiverIsUnused(context: BindingContext): Boolean = when (parent) {
     is KtSafeQualifiedExpression, is KtDotQualifiedExpression -> {
         val scopeOfApplyCall = parent.parent
-        scopeOfApplyCall == null || scopeOfApplyCall is KtBlockExpression
+        (scopeOfApplyCall == null || scopeOfApplyCall is KtBlockExpression) && !parent.isUsedAsExpression(context)
     }
     else -> false
 }
```
Comment (chao2zhang) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt]: Since KtQualifiedExpression has only two impl: `KtSafeQualifiedExpression` and `KtDotQualifiedExpression`, I am wondering if the following implementation is more concise: Smartcase can be leveraged and we do not need the extension method on `PsiElement` anymore.

```
private fun KtCallExpression.receiverIsUnused(context: BindingContext): Boolean =
    (parent as? KtQualifiedExpression)?.let {
        val scopeOfApplyCall = parent.parent
        (scopeOfApplyCall == null || scopeOfApplyCall is KtBlockExpression) &&
                (context == BindingContext.EMPTY || !it.isUsedAsExpression(context))
    } ?: false

```

Comment (t-kameyama) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt]: Thanks!

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt [hunk 2]
```diff
@@ -8,15 +8,11 @@ import io.gitlab.arturbosch.detekt.api.Issue
...
 import org.jetbrains.kotlin.lexer.KtTokens
-import org.jetbrains.kotlin.psi.KtBinaryExpression
-import org.jetbrains.kotlin.psi.KtBlockExpression
-import org.jetbrains.kotlin.psi.KtCallExpression
-import org.jetbrains.kotlin.psi.KtDotQualifiedExpression
-import org.jetbrains.kotlin.psi.KtExpression
-import org.jetbrains.kotlin.psi.KtReferenceExpression
-import org.jetbrains.kotlin.psi.KtSafeQualifiedExpression
-import org.jetbrains.kotlin.psi.KtThisExpression
+import org.jetbrains.kotlin.psi.*
```
Comment (BraisGabin) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt]: Don't use * imports please

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt [hunk 3]
```diff
@@ -53,13 +55,12 @@ class UnnecessaryApply(config: Config) : Rule(config) {
...
-    is KtSafeQualifiedExpression, is KtDotQualifiedExpression -> {
+private fun KtCallExpression.receiverIsUnused(context: BindingContext): Boolean =
+    (parent as? KtQualifiedExpression)?.let {
         val scopeOfApplyCall = parent.parent
-        scopeOfApplyCall == null || scopeOfApplyCall is KtBlockExpression
-    }
-    else -> false
-}
+        (scopeOfApplyCall == null || scopeOfApplyCall is KtBlockExpression)
+                && (context == BindingContext.EMPTY || !it.isUsedAsExpression(context))
```
Comment (schalkms) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt]:
```suggestion
        (scopeOfApplyCall == null || scopeOfApplyCall is KtBlockExpression) && 
            (context == BindingContext.EMPTY || !it.isUsedAsExpression(context))
```

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt [hunk 4]
```diff
@@ -53,13 +55,12 @@ class UnnecessaryApply(config: Config) : Rule(config) {
...
-private fun KtCallExpression.receiverIsUnused(): Boolean = when (parent) {
-    is KtSafeQualifiedExpression, is KtDotQualifiedExpression -> {
+private fun KtCallExpression.receiverIsUnused(context: BindingContext): Boolean =
+    (parent as? KtQualifiedExpression)?.let {
         val scopeOfApplyCall = parent.parent
-        scopeOfApplyCall == null || scopeOfApplyCall is KtBlockExpression
-    }
-    else -> false
-}
+        (scopeOfApplyCall == null || scopeOfApplyCall is KtBlockExpression) &&
```
Comment (schalkms) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryApply.kt]:
```suggestion
        (scopeOfApplyCall == null || scopeOfApplyCall is KtBlockExpression) &&
```
