### PR TITLE
Remove YAML Extension Requirement

### LINKED ISSUE #2417: file does not end with .yml!
Trying to load a `.yaml` file leads to an exception with the message from the issue title. [The official YAML FAQ recommends `.yaml` over `.yml`](https://yaml.org/faq.html) and I also believe that it is not up to detekt to prescribe what the file extension has to be. This choice should be up to the project. 😊

### PR DESCRIPTION
**Pull request by Fleshgrinder**
Closes #2417

### CODE REVIEW

File: detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/YamlConfig.kt [hunk 1]
```diff
@@ -41,14 +41,11 @@ class YamlConfig internal constructor(
...
 
-        private const val YAML = ".yml"
-
         /**
-         * Factory method to load a yaml configuration. Given path must exist and end with "yml".
+         * Factory method to load a yaml configuration. Given path must exist.
          */
         fun load(path: Path): Config {
             require(Files.exists(path)) { "Unable to load config from '$path': file does not exist!" }
-            require(path.toString().endsWith(YAML)) { "Invalid config file name $path: file does not end with $YAML!" }
```
Comment (schalkms) [inline detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/YamlConfig.kt]: I'd rewrite it to

```kotlin
require(path.toString().endsWith(YAML || YML)) { "Invalid config file name $path: file does not end with $YAML!" }
```

We should apply a defensive programming style here.

Comment (Fleshgrinder) [reply detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/YamlConfig.kt]: File extensions have no meaning by definition, we can have a perfectly valid YAML files with no extension `.detekt` or one that provides some defaults `detekt.yaml.dist` or … it really shouldn’t be up to the project to decide. Either parsing succeeds, or not, but the extension plays no role in it because parsing may fail despite having a `.yml` extension. In fact, just because it has a `.yml` extension does not mean that the content is YAML in the first place. 😊

Comment (schalkms) [reply detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/YamlConfig.kt]: True, although it's not common to do so. The yaml parser handles invalid tokens in the yaml configuration and thus throws an exception.
I really like the provided sanity checks. 👍

**Comment by Fleshgrinder** [comment]
Generating documentation failed for me because it only works with Java 8. You might want to consider adding a `.java-version` file to support http://www.jenv.be/ and automate the JVM selection for you and your users.
