### PR TITLE
Fix TrailingWhitespace reported position

### LINKED ISSUE #1979: TrailingWhitespace reports incorrect line number
```kotlin
package cases

// reports 1 - line with just one space
 
// reports 1 - a comment with trailing space
// A comment 
// reports 1
class TrailingWhitespacePositive { 
	// reports 1 - line with just one tab
    
    // reports 1
	fun myFunction() { 
		// reports 1 - line with 1 trailing tab
		println("A message")	
	// reports 1
	}  
}
```

## Expected Behavior
```kotlin
package cases

// reports 1 - line with just one space
 
// reports 1 - a comment with trailing space
// A comment 
// reports 1
class TrailingWhitespacePositive { 
	// reports 1 - line with just one tab
    
    // reports 1
	fun myFunction() { 
		// reports 1 - line with 1 trailing tab
		println("A message")	
	// reports 1
	}  
}
```

This file should report 6 Trailing errors in the positions:

(4, 1), (6, 13), (8, 35), (10, 1), (12, 23) and (14, 29)

## Observed Behavior
It reports 7 and in other positions.

## Steps to Reproduce
You can check this comparison: https://github.com/arturbosch/detekt/compare/master...BraisGabin:trailing-whitespace

## Context
I found this problem developing the snippet html report. Screenshot:

Captura de pantalla 2019-10-04 a las 23 53 41

## Your Environment

* Version of detekt used: 1.0.1
* Operating System and version: Mac

### PR DESCRIPTION
**Pull request by BraisGabin**
This PR fixes #1979

### CODE REVIEW

**Comment by schalkms** [comment]
Thanks for picking this up! 
I just scrolled quickly over the changes. At first glance, I'd say that this is a nice fix.
I'll take a closer look at this PR tomorrow.

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt [hunk 1]
```diff
@@ -23,23 +23,28 @@ class TrailingWhitespace(config: Config = Config.empty) : Rule(config) {
...
                 }
             }
             offset += 1 /* '\n' */
         }
     }
 
-    private fun hasTrailingWhitespace(line: String) =
-            line.isNotEmpty() && (line.last() == ' ' || line.last() == '\t')
+    private fun countTrailingWhitespace(line: String): Int {
+        return line.length - line.indexOfLast { it != ' ' && it != '\t' } - 1
```
Comment (schalkms) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt]: What happens if a whitespace is the second to last character in a line?
This might be a good test case for the negative scenario.

```Kotlin
println("Hello") ;
```

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt [hunk 2]
```diff
@@ -23,23 +23,28 @@ class TrailingWhitespace(config: Config = Config.empty) : Rule(config) {
...
-                if (ktElement != null) {
-                    if (!ktElement.isPartOfString()) {
-                        report(CodeSmell(issue, Entity.from(ktElement), createMessage(index)))
+                if (ktElement == null || !ktElement.isPartOfString()) {
+                    val entity = Entity.from(file, offset - trailingWhitespaces).let { entity ->
+                        entity.copy(
+                            location = entity.location.copy(
+                                text = entity.location.text.copy(end = offset)
+                            )
+                        )
```
Comment (schalkms) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt]: I'm not sure why there's a need for copying the entity location and the entity text?
Could you please explain this to me?

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt [hunk 3]
```diff
@@ -20,10 +22,28 @@ class TrailingWhitespaceSpec : Spek({
...
+            it("should report the correct text location") {
+                assertThat(rule.findings).hasTextLocations(
+                    55 to 56,
+                    114 to 115,
+                    163 to 164,
+                    204 to 208,
+                    245 to 246,
+                    311 to 312,
+                    329 to 331
+                )
```
[the remark this answers is not in the document]
Comment (BraisGabin) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt]: I think that I can remove the other one. Because `hasSourceLocations` didn't check the end of the finding and I wrote code to set that value properly. But I agree both checks are not needed.

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt (hunk 1 above)
Comment (BraisGabin) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt]: Done

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt (hunk 2 above)
Comment (BraisGabin) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt]: Sure, I'm using the `KtFile` as the entity for this finding. For that reason `Location.from` returns me the end of the file as the end of the finding. I need to correct that doing this. The start is set correctly because I'm using the argument `offset`.

I'm not a huge fan of this code... any better idea about how to create this finding?

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt (hunk 3 above)
[the remark this answers is not in the document]
Comment (schalkms) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt]: Please keep the other assertion. This one is so hard to maintain and not obvious when not looking over it.

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt (hunk 2 above)
Comment (schalkms) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt]: I'm not sure. Maybe @arturbosch has an idea.

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt (hunk 3 above)
[the remark this answers is not in the document]
Comment (BraisGabin) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt]: Done

[the remark this answers is not in the document]
Comment (schalkms) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt]: Sorry for nagging you once more. 
My previous post wasn't clearly formulated.
The following assertion should be removed, since we have the `hasSourceLocation` assertion.
The rest looks fine.

```Kotlin
assertThat(rule.findings).hasTextLocations(
                     55 to 56,
                     114 to 115,
                     163 to 164,
                     204 to 208,
                     245 to 246,
                     311 to 312,
                     329 to 331
                 )
```

[the remark this answers is not in the document]
Comment (BraisGabin) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt]: I can not remove it. Otherwise this code is not tested:

```kotlin
                    Entity.from(file, offset - trailingWhitespaces).let { entity ->
                        entity.copy(
                            location = entity.location.copy(
                                text = entity.location.text.copy(end = offset)
                            )
                        )
```

`hasSourceLocation` only tests the beginning of the assertion, but doesn't test the end. And, as you can see, I have code that set the end.

I understand your point and I don't like this test neither. What do you think about removing this huge test and create 7 small ones (one per finding)?

[the remark this answers is not in the document]
Comment (schalkms) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt]: Good to know.
I think this is a nice idea.
Separating the test case into smaller ones would be even better!

[the remark this answers is not in the document]
Comment (BraisGabin) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespaceSpec.kt]: Done

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt (hunk 2 above)
Comment (arturbosch) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt]: Would the new `Entity.from(PsiElement, Location)` (#2083) help here without copying the entity?

Comment (BraisGabin) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt]: I'm not sure, Location is a difficult class to create. I mean, I'd do somehitng like:

```kotlin
val Location = Location.from(offset - trailingWhitespaces).let { location ->
  location.copy(text = location.text.copy(end = offset)
}
val entity = Entity.from(file, location)
```

I suppose that this is a bit better... But I don't like it that much neither.

Comment (schalkms) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/TrailingWhitespace.kt]: While both options are mediocre, the last snippet is better, since we can spare 1 copy statement.
