### PR TITLE
Fix report for documented data classes property

### LINKED ISSUE #2529: UndocumentedPublicProperty reported for documented data classes property
## Expected Behavior
The following code:

```kotlin
/**
 * @property prop1 The property is documented
 */
data class MyDataClass(val prop1: String)
```

should not see any `UndocumentedPublicProperty` being reported because all properties are documented.

## Observed Behavior
Running detekt reports an issue:

```
UndocumentedPublicProperty - [prop1] at /home/me/workspace/project/src/main/kotlin/Example.kt:8:24
```

## Steps to Reproduce
The code above is all you need to reproduce the issue.

## Context
I was trying to update detekt from `1.6.0` to `1.7.1` and I got this errors. But I cannot fix them, because the properties are already documented.

## Your Environment
* Version of detekt used: `1.7.1`
* Version of Gradle used: `6.3`
* Operating System and version: `linux 5.5.11`
* Link to your project: https://github.com/jcornaz/kwik/pull/141

### PR DESCRIPTION
**Pull request by schalkms**
A documented property should not be reported as undocumented by the UndocumentedPublicProperty rule.

This closes #2529

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/documentation/UndocumentedPublicPropertySpec.kt [hunk 1]
```diff
@@ -125,10 +123,12 @@ class UndocumentedPublicPropertySpec : Spek({
         it("does not report documented public properties in a primary constructor") {
             val code = """
                 /**
-                * @a int1
-                * [b] int2 
+                * @property a int1
+                * [b] int2
+                * @property [c] int3
+                * @param d int4
```
Comment (BraisGabin) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/documentation/UndocumentedPublicPropertySpec.kt]: If `d`is just documented as parameter... we should flag it, right? I mean, we want to document the properties.

And probably it would be better to split this test in 4.

Comment (schalkms) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/documentation/UndocumentedPublicPropertySpec.kt]: As always, thanks for the review. Please see my comment in the referenced issue.
https://github.com/arturbosch/detekt/issues/2529#issuecomment-605294205

Splitting the test case up makes sense.
