### PR TITLE
Change --filters argument to only check relative paths

### LINKED ISSUE #1212: Filters apply to absolute paths not relative paths
## Expected Behavior
Filters apply only to relative paths.

## Current Behavior
Filters apply to absolute paths.

## Steps to Reproduce (for bugs)
Identified investigating #1158 (relevant build log: https://travis-ci.org/arturbosch/detekt/jobs/432263468)

## Context
The filters set when Travis build runs includes `.*/build/*.`. Travis checks out the build at `/home/travis/build/arturbosch/detekt` which is also detekt's working directory when it runs. I'd expected that it's filtering based on the relative path, but it appears to be filtering based on the absolute path. Since all Kotlin files have `/build/` in their absolute paths, everything is filtered.

## Your Environment
* Version used: master
* Operating System and version: Ubunty Trusty 14.04 (running on Travis)
* Link to your project: See #1158 and build log: https://travis-ci.org/arturbosch/detekt/jobs/432263468

### PR DESCRIPTION
**Pull request by Mauin**
Fixes #1212 and should therefore also allow Travis to again check files during the CI build.

This change will make the `--filters` argument only operate on the relative path to from the current directory.
This would be:
 - Possibly wherever the user currently invokes the CLI from manually
 - The root of the project/module if using the Gradle plugin

### CODE REVIEW

**Comment by Mauin** [comment]
Just checked the green Travis build and with this change it actually analyzes files again.

File: detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Configurations.kt [hunk 1]
```diff
@@ -15,7 +15,7 @@ fun CliArgs.createPathFilters(): List<PathFilter> = filters.letIfNonEmpty {
 			.asSequence()
 			.map { it.trim() }
 			.filter { it.isNotEmpty() }
-			.map(::PathFilter)
+			.map { filter -> PathFilter(filter) }
```
Comment (arturbosch) [inline detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Configurations.kt]: Should't the root here now be the `input` parameter?

Comment (arturbosch) [reply detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Configurations.kt]: Paths.get("").toAbsolutePath() could be different than the input parameter?
btw didn't know that Paths.get("") worked :)

Comment (Mauin) [reply detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Configurations.kt]: It could be. As mentioned in the PR description. The root in this case will be wherever you're invoking the CLI from. Alternatively we can pass a `--root` argument to the CLI. But then we start adding more and more obscure arguments only needed for special cases.
