### PR TITLE
Fix SpacingBetweenPackageAndImports issue for KTS

### LINKED ISSUE #1937: Bogus SpacingBetweenPackageAndImports violation for KTS without package
## Expected Behavior

`SpacingBetweenPackageAndImports` should not be reported if no `package` directive is present.

## Observed Behavior

`SpacingBetweenPackageAndImports` is reported for a KTS (Kotlin Script) file which has no `package` directive at all.

## Steps to Reproduce

- Clone https://github.com/heremaps/oss-review-toolkit and checkout the `detekt-issue-1937` branch.
- Run `./gradlew :spdx-utils:detekt`.
- Observe:

```
21 kotlin files were analyzed.
Ruleset: style - 5min debt
   SpacingBetweenPackageAndImports - [Build_gradle] at oss-review-toolkit/spdx-utils/build.gradle.kts:12:22
```

## Context

I'm trying to let *detekt* also check my Gradle Kotlin Script build files, not only main Kotlin files.

## Your Environment

* Version of detekt used: 1.0.1
* Version of Gradle used (if applicable): 5.6.2
* Operating System and version: Ubuntu 18.04 x64
* Link to your project (if it's a public repository): https://github.com/heremaps/oss-review-toolkit/tree/detekt-issue-1937

### PR DESCRIPTION
**Pull request by schalkms**
SpacingBetweenPackageAndImports does not report for Kotlin script files.
That is because Kotlin scripts have no package directive.
This closes #1937

### CODE REVIEW

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImports.kt [hunk 1]
```diff
@@ -44,8 +44,10 @@ class SpacingBetweenPackageAndImports(config: Config = Config.empty) : Rule(conf
             Debt.FIVE_MINS)
 
     override fun visitKtFile(file: KtFile) {
-        containsClassOrObject = file.collectDescendantsOfType<KtClassOrObject>().any() == true
-        super.visitKtFile(file)
+        if (!file.isScript()) {
+            containsClassOrObject = file.collectDescendantsOfType<KtClassOrObject>().any() == true
+            super.visitKtFile(file)
```
Comment (3flex) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImports.kt]: Visiting super should not be conditional I think?

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImportsSpec.kt [hunk 2]
```diff
@@ -66,6 +67,12 @@ class SpacingBetweenPackageAndImportsSpec : Spek({
             assertThat(subject.lint(code)).hasSize(2)
         }
 
+        it("does not report for Kotlin script file") {
+            val code = "package test\nimport a.b\nclass A {}"
+            val ktsFile = KtTestCompiler.compileFromContent(code, "Test.kts")
+            assertThat(subject.lint(ktsFile)).hasSize(0)
```
Comment (3flex) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImportsSpec.kt]: `isEmpty()` instead of `hasSize(0)`

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImports.kt (hunk 1 above)
Comment (schalkms) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImports.kt]: In this case it's not necessary. I don't want to visit the import list for a Kotlin script file.

**Comment by sschuberth** [comment]
> That is because Kotlin scripts have no package directive.

First of all, thanks @3flex for working on this! But please note that Kotlin scripts actually *can* have a package directive, but they may as well omit it, in which case the code is located in the implicit root package.

With your fix, does *detekt* still report `SpacingBetweenPackageAndImports` for Kotlin scripts that *do* have a package directive but no spacing between it and the imports?

**Comment by 3flex** [comment]
I didn't author the fix, I just approved it, but that's a good point - it should apply the rule in that case.

Perhaps another rule to suggest removing the package directive, if it truly has no purpose in scripts?

**Comment by sschuberth** [comment]
Ah, sorry, I was meaning to ping @schalkms. I don't think there should be a rule that suggests to remove a `package` directive from scripts, as that's a perfectly valid way to organize larger script collections.

**Comment by schalkms** [comment]
I'm sorry. The issue description was misleading for me. I'll provide another PR.
@sschuberth may I ask you to review this PR, then? Thanks!

**Comment by sschuberth** [comment]
> @sschuberth may I ask you to review this PR, then?

Sure thing, just add me as a reviewer!
