### PR TITLE
Fix ExpressionBodySyntax when multiline expression

### LINKED ISSUE #976: ExpressionBodySyntax: false positive with includeLineWrapping in multiline expression
For something like:

```
fun foo(bar: Int): Int {
    return when (bar) {
        0 -> 1
        1 -> 2
        else -> 3
    }
}
```

## Expected Behavior
No smell should be reported

## Current Behavior
A smell is reported

From #950

### PR DESCRIPTION
**Pull request by marianosimone**
Check the body to see if it's multiline, instead of the
return expression, which might be multiline, but with
none of its children having a \n

Fixes #976

### CODE REVIEW

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt [hunk 1]
```diff
@@ -51,29 +51,26 @@ class ExpressionBodySyntax(config: Config = Config.empty) : Rule(config) {
 	private val includeLineWrapping = valueOrDefault(INCLUDE_LINE_WRAPPING, false)
 
 	override fun visitNamedFunction(function: KtNamedFunction) {
-		if (function.bodyExpression != null) {
-			val body = function.bodyExpression!!
-			body.singleReturnStatement()?.let { returnStmt ->
-				if (includeLineWrapping || !containsWhiteSpace(returnStmt.returnedExpression)) {
-					report(CodeSmell(issue, Entity.from(returnStmt), issue.description))
+		function.bodyExpression?.run body@{
```
Comment (marianosimone) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt]: I don't know how people feel about this syntax, but I much prefer it vs using `if` and `!!`

Comment (marianosimone) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt]: I don't know how people feel about the use of labels like this.. but I prefer it over `if` and `!!`

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntaxSpec.kt [hunk 2]
```diff
@@ -51,7 +51,7 @@ class ExpressionBodySyntaxSpec : SubjectSpek<ExpressionBodySyntax>({
 					if (true) return true
 					return false
 				}
-			""")).hasSize(0)
+			""")).isEmpty()
```
Comment (marianosimone) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntaxSpec.kt]: feels more semantic to use `isEmpty` than `hasSize(0)` :man_shrugging:

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt (hunk 1 above)
Comment (schalkms) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt]: It increases the complexity of the code. I prefer the previously used style.
We also have a rule for reporting labeled expressions.

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntaxSpec.kt [hunk 3]
```diff
@@ -65,7 +65,27 @@ class ExpressionBodySyntaxSpec : SubjectSpek<ExpressionBodySyntax>({
...
+	}
+
+	given("several return statements with multiline expression") {
+
+		val code = """
+			fun stuff(val arg: Int): Int {
+				return when(arg) {
+					0 -> 0
+					else -> 1
+				}
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntaxSpec.kt]: Can we also test this with `return if .. else ..` ?

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt [hunk 4]
```diff
@@ -51,29 +51,26 @@ class ExpressionBodySyntax(config: Config = Config.empty) : Rule(config) {
...
 	private fun KtExpression.singleReturnStatement(): KtReturnExpression? {
 		val statements = (this as? KtBlockExpression)?.statements
-		return statements?.size?.let {
-			if (it == 1 && statements[0] is KtReturnExpression) {
-				return statements[0] as KtReturnExpression
-			} else null
-		}
+		return statements
+				?.takeIf { it.size == 1 }
+				?.let { it[0] as? KtReturnExpression }
```
Comment (schalkms) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt]: Refactored nicely

**Comment by schalkms** [comment]
Thanks for the quick fix 👍

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntaxSpec.kt (hunk 3 above)
Comment (marianosimone) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntaxSpec.kt]: done!

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt (hunk 1 above)
Comment (marianosimone) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt]: Ok.. rolled back this (but did change the `let` for `run`... specially since we don't need the `returnStmt` any more, I think `run` is more idiomatic

Comment (marianosimone) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt]: Interestingly enough, `detecktCheck` did not complain about the labeled expressions... maybe there's something wrong with the config?

**Comment by marianosimone** [comment]
changes applied
