### PR TITLE
Fix SpacingBetweenPackageAndImports issue for scripts without packages

### LINKED ISSUE #1937: Bogus SpacingBetweenPackageAndImports violation for KTS without package
## Expected Behavior

`SpacingBetweenPackageAndImports` should not be reported if no `package` directive is present.

## Observed Behavior

`SpacingBetweenPackageAndImports` is reported for a KTS (Kotlin Script) file which has no `package` directive at all.

## Steps to Reproduce

- Clone https://github.com/heremaps/oss-review-toolkit and checkout the `detekt-issue-1937` branch.
- Run `./gradlew :spdx-utils:detekt`.
- Observe:

```
21 kotlin files were analyzed.
Ruleset: style - 5min debt
   SpacingBetweenPackageAndImports - [Build_gradle] at oss-review-toolkit/spdx-utils/build.gradle.kts:12:22
```

## Context

I'm trying to let *detekt* also check my Gradle Kotlin Script build files, not only main Kotlin files.

## Your Environment

* Version of detekt used: 1.0.1
* Version of Gradle used (if applicable): 5.6.2
* Operating System and version: Ubuntu 18.04 x64
* Link to your project (if it's a public repository): https://github.com/heremaps/oss-review-toolkit/tree/detekt-issue-1937

### PR DESCRIPTION
**Pull request by schalkms**
Both a Kotlin file and a Kotlin script can be declared with and without
a package declaration. This commit checks if the class even contains a
package declaration for both .kt and .kts files.
Closes #1937

### CODE REVIEW

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImports.kt [hunk 1]
```diff
@@ -44,8 +44,10 @@ class SpacingBetweenPackageAndImports(config: Config = Config.empty) : Rule(conf
             Debt.FIVE_MINS)
 
     override fun visitKtFile(file: KtFile) {
-        containsClassOrObject = file.collectDescendantsOfType<KtClassOrObject>().any() == true
-        super.visitKtFile(file)
+        if (file.packageDirective != null) {
+            containsClassOrObject = file.collectDescendantsOfType<KtClassOrObject>().any() == true
+            super.visitKtFile(file)
```
Comment (sschuberth) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImports.kt]: Just asking: Is it correct to include the `super`-call into the `if`, or should it maybe be called in any case?

Comment (schalkms) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImports.kt]: Thanks for the review.
In this case it's not necessary. I don't want to visit the import list for a Kotlin script file.

Comment (sschuberth) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/SpacingBetweenPackageAndImports.kt]: Ok, then all looks good to me, thanks!
