### PR TITLE
Restrict Postfix operators to ++ and -- - closes #491

### LINKED ISSUE #491: UselessPostfixExpression rule will detekt a wrong expression like “mInstance!!”

### PR DESCRIPTION
**Pull request by arturbosch**

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/UselessPostfixExpressionSpec.kt [hunk 1]
```diff
@@ -64,5 +64,14 @@ class UselessPostfixExpressionSpec : SubjectSpek<UselessPostfixExpression>({
 				"""
 			assertThat(subject.lint(code)).hasSize(1)
 		}
+
+		it("should only detect ++ or -- postfix operator") {
+			val code = """
+				fun getInstance(): SwiftBrowserIdleTaskHelper {
+					return sInstance!!
```
Comment (Mauin) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/UselessPostfixExpressionSpec.kt]: Can you add one line here that simply does `sInstance!!`? Just to check that the current postfix is not ignored because of the `return`

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/UselessPostfixExpression.kt [hunk 2]
```diff
@@ -41,8 +43,11 @@ class UselessPostfixExpression(config: Config = Config.empty) : Rule(config) {
 				?.forEach { report(it) }
 	}
 
+	private fun KtExpression.asPostFixExpression() = if (this is KtPostfixExpression &&
```
Comment (Mauin) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/UselessPostfixExpression.kt]: nit: Sort the private method below the overriden methods.

**Comment by Mauin** [comment]
Awesome, thanks!
