### PR TITLE
UseDataClass: fix false positive with `copy` function

### LINKED ISSUE #1040: False-positive for UseDataClass: `copy` shouldn't be considered a default function
One of the rules to check if we should use a data class is to check if the class only contains "default functions": https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClass.kt#L56

I understand why `hashCode`, `equals` and `toString` are there, but Kotlin's data class `copy` is not an overridable function.

False-positive class:
```
class Clipboard(private val type: Int) {
    fun copy(text: String) = Unit
}
```

I think `copy` could be removed from the list of default functions since it's not overridable.

What do you think?

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #1040

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt [hunk 1]
```diff
@@ -137,6 +144,73 @@ class UseDataClassSpec : Spek({
...
+            it("does report with copy method") {
+                val code = """
+                    class D(val a: Int, val b: String) {
+                        fun copy(a: Int, b: String): D = D(a, b)
+                    }
+                """
+                assertThat(subject.compileAndLintWithContext(wrapper.env, code)).hasSize(1)
+            }
+
+            it("does report with copy method which has implicit return type") {
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt]:
```suggestion
            it("does report with copy method which has an implicit return type") {
```

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt [hunk 2]
```diff
@@ -137,6 +144,73 @@ class UseDataClassSpec : Spek({
...
+            it("does not report with copy method which has different parameter types 2") {
+                val code = """
+                    class D(val a: Int, val b: String) {
+                        fun copy(a: Int, b: String?): D = D(a, b.toString())
+                    }
+                """
+                assertThat(subject.compileAndLintWithContext(wrapper.env, code)).isEmpty()
+            }
+
+            it("does not report with copy method which has different return type") {
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt]:
```suggestion
            it("does not report with copy method which has a different return type") {
```

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt [hunk 3]
```diff
@@ -137,6 +144,73 @@ class UseDataClassSpec : Spek({
...
+            it("does not report with copy method which has no parameters") {
+                val code = """
+                    class D(val a: Int, val b: String) {
+                        fun copy(): D = D(0, "")
+                    }
+                """
+                assertThat(subject.compileAndLintWithContext(wrapper.env, code)).isEmpty()
+            }
+
+            it("does not report with copy method which has parameters more than primary constructor") {
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt]:
```suggestion
            it("does not report with copy method which has more parameters than the primary constructor") {
```
