### PR TITLE
Fix ExplicitCollectionElementAccessMethod crash

### LINKED ISSUE #2301: ExplicitCollectionElementAccessMethod crashes
## Expected Behavior
`ExplicitCollectionElementAccessMethod` rule should run on Kotlin code which compiles

## Observed Behavior
`ExplicitCollectionElementAccessMethod` is crashing on Kotlin code which compiles

## Steps to Reproduce
Run `ExplicitCollectionElementAccessMethod` rule on the following code snippet
```kotlin
@file:Suppress("TooManyFunctions")
@file:JvmName("FieldUtil")

package <redacted>.common.util

import androidx.databinding.ObservableBoolean
import androidx.databinding.ObservableField
import androidx.databinding.ObservableInt
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.asLiveData
import <redacted>.common.binding.InputField
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.onEach

fun <T> Flow<T>.asInputField(
    scope: CoroutineScope
): InputField<T> = InputField<T>().apply {
    this@asInputField.onEach {
        this@apply.set(it)
    }
    .launchIn(scope)
}

fun <T> Flow<T>.asMutableLiveData(): MutableLiveData<T> = asLiveData() as MutableLiveData<T>

fun <T> ObservableField<T>.require(): T = get()
    ?: throw IllegalArgumentException("Value is not set")

fun ObservableInt.require(): Int = get()

fun ObservableBoolean.require(): Boolean = get()
```

It will result in this crash:
```kotlin
Analyzing '<redacted>/common/util/FieldUtil.kt' led to an exception.
The original exception message was: dotExpression must not be null
Running detekt '1.5.0' on Java '1.8.0_221-b11' on OS 'Mac OS X'.
If the exception message does not help, please feel free to create an issue on our GitHub page.
io.gitlab.arturbosch.detekt.rules.style.ExplicitCollectionElementAccessMethod.isMapMethod(ExplicitCollectionElementAccessMethod.kt:65)
io.gitlab.arturbosch.detekt.rules.style.ExplicitCollectionElementAccessMethod.visitCallExpression(ExplicitCollectionElementAccessMethod.kt:53)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitCallExpression(KtVisitorVoid.java:797)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitCallExpression(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
org.jetbrains.kotlin.psi.KtElementImpl.accept(KtElementImpl.java:51)
org.jetbrains.kotlin.com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
org.jetbrains.kotlin.psi.KtTreeVisitorVoid.visitElement(KtTreeVisitorVoid.java:25)
org.jetbrains.kotlin.psi.KtVisitor.visitKtElement(KtVisitor.java:24)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtElement(KtVisitorVoid.java:25)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtElement(KtVisitorVoid.java:447)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtElement(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:182)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitExpression(KtVisitorVoid.java:169)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitExpression(KtVisitorVoid.java:659)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitExpression(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtVisitor.visitBinaryExpression(KtVisitor.java:218)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitBinaryExpression(KtVisitorVoid.java:205)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitBinaryExpression(KtVisitorVoid.java:713)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitBinaryExpression(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtBinaryExpression.accept(KtBinaryExpression.java:35)
org.jetbrains.kotlin.psi.KtElementImpl.accept(KtElementImpl.java:51)
org.jetbrains.kotlin.com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
org.jetbrains.kotlin.psi.KtTreeVisitorVoid.visitElement(KtTreeVisitorVoid.java:25)
org.jetbrains.kotlin.psi.KtVisitor.visitKtElement(KtVisitor.java:24)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtElement(KtVisitorVoid.java:25)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtElement(KtVisitorVoid.java:447)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtElement(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:182)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitExpression(KtVisitorVoid.java:169)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitExpression(KtVisitorVoid.java:659)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitExpression(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtVisitor.visitDeclaration(KtVisitor.java:29)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:29)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:453)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtVisitor.visitNamedDeclaration(KtVisitor.java:398)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedDeclaration(KtVisitorVoid.java:381)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedDeclaration(KtVisitorVoid.java:959)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedDeclaration(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtVisitor.visitNamedFunction(KtVisitor.java:53)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:49)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:483)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:50)
org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:59)
org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
org.jetbrains.kotlin.com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:733)
org.jetbrains.kotlin.psi.KtTreeVisitorVoid.visitElement(KtTreeVisitorVoid.java:25)
org.jetbrains.kotlin.com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
org.jetbrains.kotlin.psi.KtVisitor.visitKtFile(KtVisitor.java:73)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:69)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:513)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:242)
org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:229)
io.gitlab.arturbosch.detekt.api.BaseRule.visit(BaseRule.kt:53)
io.gitlab.arturbosch.detekt.api.BaseRule.visitFile(BaseRule.kt:43)
io.gitlab.arturbosch.detekt.api.RuleSet.accept(RuleSet.kt:35)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:76)
io.gitlab.arturbosch.detekt.core.Detektor.runSync(Detektor.kt:44)
io.gitlab.arturbosch.detekt.core.Detektor.run(Detektor.kt:28)
io.gitlab.arturbosch.detekt.core.DetektFacade.run(DetektFacade.kt:41)
io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:39)
io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:16)
```

## Your Environment

* Version of detekt used: 1.5.0
* Version of Gradle used (if applicable): 6.1
* Operating System and version: 10.14.6

### PR DESCRIPTION
**Pull request by schalkms**
The rule shouldn't crash for getter and setter that have no parent expression.
Fixes #2301

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExplicitCollectionElementAccessMethodSpec.kt [hunk 1]
```diff
@@ -207,4 +207,21 @@ class ExplicitCollectionElementAccessMethodSpec : Spek({
...
+            """
+            assertThat(subject.compileAndLintWithContext(wrapper.env, code)).isEmpty()
+        }
+    }
 })
+
+class A {
+    val i1: Int? = get() ?: throw IllegalArgumentException()
+    val i2: Int = get()
+}
```
Comment (BraisGabin) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExplicitCollectionElementAccessMethodSpec.kt]: 🤔 I think that you forgot to remove this
