### PR TITLE
Fix UseDataClass false positive (delegation)

### LINKED ISSUE #1585: UseDataClass false positive
A delegate is used to save data in Android shared preferences, so this class should not be a data class.

## Expected Behavior
Do not report this as a rule violation

## Observed Behavior
Reports as a rule violation

## Steps to Reproduce
```
class SharedPreferenceRepository(
    context: Context
) {
    companion object {
        private const val PREFIX = "APP"
        private const val INSTALL_UUID: String = "${PREFIX}_INSTALL_UUID"
    }

    private var _installUUID: String by SharedPreferencesExtension(context, INSTALL_UUID, "")
}
```

### PR DESCRIPTION
**Pull request by schalkms**
A class containing delegated properties is no data class candidate.
This closes #1585

### CODE REVIEW

**Comment by schalkms** [comment]
CodeFactor does not rerun when I force it. Interesting..

File: detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClass.kt [hunk 1]
```diff
@@ -93,12 +94,6 @@ class UseDataClass(config: Config = Config.empty) : Rule(config) {
                 klass.secondaryConstructors.all { it.isPrivate() }
     }
 
-    private fun KtClass.doesNotExtendAnything() = superTypeListEntries.isEmpty()
-
-    private fun KtClass.isClosedForExtension() = !isAbstract() && !isOpen()
-
-    private fun KtClass.extractDeclarations(): List<KtDeclaration> = body?.declarations.orEmpty()
```
Comment (arturbosch) [inline detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClass.kt]: These weren't used?

Comment (schalkms) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClass.kt]: I moved them to the utility class `KtClassOrObjectExtensions.kt`.

Comment (arturbosch) [reply detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClass.kt]: ah I see
